repos:
  - repo: local
    hooks:
      - id: spotless
        name: spotlessApply
        entry: ./gradlew spotlessApply
        language: system
        stages: [commit]
        pass_filenames: false